### ISSUE TITLE
Build from source with MinGW

### ISSUE THREAD

**Issue by htzh** [honnibal/spaCy#132] opened 2015-10-08 04:38 UTC
I am trying to build from source under MinGW. I noticed that Cython seems to have trouble with relative import sometimes, but not all the times. I am not using virtualenv as I have installed the dependencies into my system. I am not sure if that might have something to do with this. Anyway this is what I am encountering:

First I ran into this:
```
Error compiling Cython file:
------------------------------------------------------------
...
from ..vocab cimport Vocab
^
------------------------------------------------------------

spacy/serialize/packer.pxd:1:0: 'vocab.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from ..vocab cimport Vocab
^
------------------------------------------------------------

spacy/serialize/packer.pxd:1:0: 'vocab/Vocab.pxd' not found
```

So I edited it to use absolute path for the module:
```
--- a/spacy/serialize/packer.pxd
+++ b/spacy/serialize/packer.pxd
@@ -1,4 +1,4 @@
-from ..vocab cimport Vocab
+from spacy.vocab cimport Vocab
```
and the compile then succeeded. I also had to do the same for  ```spacy/syntax/transition_system.pxd``` and ```spacy/tokens/doc.pxd```. I was able to compile the following DLLs:
```
$ ls spacy/*.dll
spacy/_ml-cpython-34m.dll      spacy/morphology-cpython-34m.dll
spacy/_theano-cpython-34m.dll  spacy/orth-cpython-34m.dll
spacy/attrs-cpython-34m.dll    spacy/parts_of_speech-cpython-34m.dll
spacy/cfile-cpython-34m.dll    spacy/strings-cpython-34m.dll
spacy/gold-cpython-34m.dll     spacy/tagger-cpython-34m.dll
spacy/lexeme-cpython-34m.dll   spacy/tokenizer-cpython-34m.dll
spacy/matcher-cpython-34m.dll  spacy/vocab-cpython-34m.dll
```

Now I am having trouble with
```
spacy/syntax/ner.cpp: In function 'int __pyx_f_5spacy_6syntax_3ner_13BiluoPushDown_preprocess_gold(__pyx_obj_5spacy_6syntax_3ner_BiluoPushDown*, __pyx_obj_5spacy_4gold_GoldParse*)':
spacy/syntax/ner.cpp:3532:38: error: no match for 'operator=' (operand types are '__pyx_t_5spacy_24syntax_dot_transition_system_Transition' and '__pyx_t_5spacy_6syntax_17transition_system_Transition')
     (__pyx_v_gold->c.ner[__pyx_v_i]) = __pyx_t_4;
```
which looks like it that it could be an issue related to imported names?

I wonder if you have seen this kind of problems before. I use up to date Msys2/MinGW-Packages. My 
```
$ python3 --version
Python 3.4.3
$ cython --version
Cython version 0.23.beta1
```

**Comment by honnibal** [comment] 2015-10-08 04:43
Is there some equivalent of the PYTHONPATH environment variable you could be missing? I'm not quite sure how this works on Windows.

**Comment by honnibal** [comment] 2015-10-08 04:44
One way forward might be to build one of the simpler dependencies, to make sure we've got the process right.

Could you try with my package Cymem: http://github.com/syllog1sm/cymem ? That's very simple. If we can get it to work we should be in good shape, in theory.

I'm keen to support you on this, as I'd like to get the Windows install fixed.

**Comment by htzh** [comment] 2015-10-08 05:06
Thanks for the quick response. I will try cymem and report back tomorrow.

**Comment by htzh** [comment] 2015-10-08 05:10
BTW I have used Cython to wrap my own C++ library and it worked fine so I know at least my simple workflow works.

**Comment by honnibal** [comment] 2015-10-08 05:14
It might be a bit more complicated when installing off PyPi, and using dependent modules. I'm not sure.

**Comment by htzh** [comment] 2015-10-08 17:08
Good news. I upgraded my Cython to 23.3 and all the relative imports trouble have gone away. So now I am able to finish build. I will run tests later to see if they actually work.

**Comment by htzh** [comment] 2015-10-08 22:50
I am having trouble with pytest. It looks like some kind of path problem. I wonder if you have a command line to run some of the tests without using pytest just to spot check if the build was alright.

**Comment by htzh** [comment] 2015-10-09 00:53
Unfortunately the build appears incorrect. I tried to run the ```examples``` but Python ended up seg faulting without giving much information indicating where or why.

**Comment by honnibal** [comment] 2015-10-09 00:56
Did you install the data?

    python -m spacy.en.download

A very simple test is

    python -c "import spacy.en; nlp = spacy.en.English(); print([w.text for
w in nlp(u'Hello world')])"

**Comment by htzh** [comment] 2015-10-09 01:06
I am kind of curious about how you decided on doing most development in Cython, instead of say using Python/C++ (and maybe Cython as a wrapper). Indeed your project is the most starred Cython project after Cython itself, which is how I happened upon it looking for examples of Cython (though I do remember reading about your project on HN a while ago).

**Comment by honnibal** [comment] 2015-10-09 01:32
Well, that's not quite true. Mostly it's just that developers don't
advertise that the library is powered by Cython.

lxml is written by the main author of Cython, Stefan Behnel. Cython also
powers Kivy, and much of numpy. It's pretty much ubiquitous in Python
extension modules.

A pure Python library would be much too slow and too memory intensive. A
C++ core with a Python wrapping would be too inflexible. The interface
between the "C part" and the "Python part" is always changing, as the
library develops. Dropping some functionality "down" into the C++ requires
ripping the code up and rewriting. Similarity, if some functionality that
has been written in C++ needs to become more complicated, moving it to
Python involves rewriting.

So, Cython affords much much more flexibility. I don't have to predict what
needs to be fast and exactly how everything will work ahead of time. It's
very beneficial to write in a single language.

**Comment by htzh** [comment] 2015-10-09 01:47
Yes I did download the data:
```
$ du -s spacy/en/data/
870883  spacy/en/data/
```

The simple test also crashes. Unfortunately I don't have much to work with:
```
$ python3 -c "import spacy.en; nlp = spacy.en.English(); print([w.text for
> w in nlp(u'Hello world')])"
/mingw32/bin/python3: line 6:  3468 Segmentation fault      "$( dirname ${BASH_SOURCE[0]} )/python3.exe" "$@"
```

**Comment by honnibal** [comment] 2015-10-09 01:51
Okay, thanks.

The problem is I've never programmed on a Microsoft platform, and don't have ready access to a machine. We're trying to sort this out.

**Comment by htzh** [comment] 2015-10-09 01:54
No problem. I am new to Cython. As I gain a little more experience maybe something will click or tell me what could be wrong with the build. The tool chain is definitely not as mature and some parts of the abstraction are leaky.

**Comment by htzh** [comment] 2015-10-09 02:13
Meanwhile I will try out spacy in my Linux vbox.

**Comment by htzh** [comment] 2015-10-09 02:25
Would you mind telling me what you use to develop Cython code? Emacs' cython-mode does not work for me and it seems broken by the updates to python mode (cf this bug report https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-02/msg00679.html). Both C++ and Python have great tooling and ide support.

**Comment by honnibal** [comment] 2015-10-09 03:24
I use vim. I'm told if you want an IDE, PyCharm is pretty good.

**Comment by htzh** [comment] 2015-10-09 04:07
I just tried it on my ArchLinux vbox. Build went very similar to MinGW. I got a core dump as well. The difference is I did get the print-out first (which may just be due to the difference in I/O buffering and how seg fault is handled). I use 32 bit systems. Is there anything 64 bit specific? Are you also using the newest Cython (0.23.3)?

```
python -c "import spacy.en; nlp = spacy.en.English(); print([w.text for w in nlp(u'Hello world')])"
['Hello', 'world']
*** Error in `python': free(): invalid next size (fast): 0x18cd2880 ***
======= Backtrace: =========
```

**Comment by honnibal** [comment] 2015-10-09 04:12
Everything worked on 32bit last time I checked a couple of weeks ago. Let
me try again.

**Comment by htzh** [comment] 2015-10-09 04:17
Also I used pip for all the dependencies including cymem. I didn't build cymem from source.

**Comment by htzh** [comment] 2015-10-09 04:36
I was able to build and run the simple command line test under 64 bit MinGW without crashing. But on this system the 64 bit numpy support is considered experimental:
```
$ python3 -c "import spacy.en; nlp = spacy.en.English(); print([w.text for
  w in nlp(u'Hello world')])"
_frozen_importlib:321: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
['Hello', 'world']
```

So the crash appears to be 32 bit specific rather than Windows specific.

**Comment by honnibal** [comment] 2015-10-09 04:46
Replicated with the following on 32bit Debian Weezy:

 ```bash
sudo apt-get update
sudo apt-get build-essential python-dev python-virtualenv
virtualenv .env
source .env/bin/activate
pip install spacy
python -m spacy.en.download all
python -c "import spacy.en; nlp = spacy.en.English(); print([w.text for w in nlp(u'Hello world')])"
```

I had this working just a few weeks back. Strange.

Investigating.

**Comment by htzh** [comment] 2015-10-09 04:57
My 64 bit MinGW also does not work normally. I ran it interactively at the Python prompt:
```
>>> nlp = spacy.en.English()
>>> example = u"I prefer Siri to Google Now. I'll google now to find out how the google now service works."
```
It terminates silently after the assignment. Strange. Do you overload any relevant Python function? The ```nlp=...``` takes a long time but didn't crash.

**Comment by honnibal** [comment] 2015-10-09 05:06
If it's terminating like that, it would be because there's still a memory error in the 64bit version for you. It's just that the corruption hasn't caused a problem initially.

**Comment by htzh** [comment] 2015-10-09 05:15
Yes sounds like memory corruption. Seems like the ```hello world``` example was just a lucky fluke. If I run a longer sentence it also silently dies.
```
$ python3 -c "import spacy.en; nlp = spacy.en.English(); print([w.text for
 w in nlp(u'I prefer Siri to Google Now.')])" 
['I', 'prefer', 'Siri', 'to', 'Google', 'Now', '.']

$ python3 -c "import spacy.en; nlp = spacy.en.English(); print([w.text for
 w in nlp(u'I google now to find out how the google now service works.')])"
...dies silently...
```
Maybe just depends on when GC was triggered.

**Comment by honnibal** [comment] 2015-10-09 05:28
Yep.

Anyway. I have it replicated and I'm working on it.

**Comment by honnibal** [comment] 2015-10-09 05:54
Can you pull from master and rebuild? It's now working for me when I build from source on 32bit.

**Comment by maxirmx** [comment] 2015-10-09 05:55
Python 2.7 64 bit build with MinGW has module compatibility problem  (32/64)
I can magically mask it but the build crashes one way or another.  You may be experiencing this or similar problem with Python 3 in addition to the issue honnibal has fixed.

**Comment by htzh** [comment] 2015-10-09 06:03
I noticed that the 64 bit python image after ```nlp = spacy.en.English()``` is 1.98GB. So it is possible that the 32 bit version is simply pushing beyond the memory limit (I believe 2GB on Windows). Did you recently update the data file that could explain the different in memory usage? But anyway this likely implies not much value can be had in making 32 bit version working well.

I am curious if you can also replicate what I observed for the 64 bit version. Or is it just my system.having the problem?

**Comment by htzh** [comment] 2015-10-09 06:12
Cool. Whatever you did fixed the core dump on my 32 bit Linux. Plus now I can run the 64 bit windows build on 
```
$ python3 matcher_example.py
_frozen_importlib:321: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
Before
Google ORG ['NNP']
google ORG ['VB']
google ORG ['NNP']
After
Google Now PRODUCT ['NNP', 'RB']
google ORG ['VB']
google now PRODUCT ['NNP', 'RB']
Sydney True
sydney False
Sydney True
sydney True
SYDNEY True
the Brisbane Broncos ORG
the South Darwin Spiders ORG
```
Will investigate more tomorrow. Good work!

**Comment by htzh** [comment] 2015-10-09 18:26
Unfortunately 32 bit mingw build still seg faults. So currently what I have is:

1. MinGW builds okay. I use MSYS2/MINGW-packages. One needs to ```pip3 install cython --upgrade``` to get the latest Cython. The version that came with ```pacman``` (0.23.beta1) does not work. Cython that comes with MINGW packages has slightly different command line behavior (see https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-cython/PKGBUILD#L26-L37) but I have so far not experienced any problem with using pip installed version.

1. 64 bit executable can run ```examples```; 32 bit version still crashes on Windows. pytest does not work with either of my environment so I can't run the more complete test suite.

**Comment by htzh** [comment] 2015-10-09 18:41
On Linux the 32 bit version virtual memory usage after ```nlp = spacy.en.English()``` is 1.67GB so the 32 bit image is smaller than the 64 bit one. It is therefore unlikely the direct cause of the 32 bit crash when built under MinGW.

**Comment by maxirmx** [comment] 2015-10-10 18:50
I made 'clean' builds for Python 2.7 using MS and MinGW toolchains.
If there are real batch file lovers around, MS version is here: https://github.com/maxirmx/spaCy
Be careful - there is a change in setup.py not merged with Linux setup

Behaviour is the same - 64 bit version works, 32 bit version crashes
Considering the number of type conversion warnings I suspect that the data files are not compatible with 32 bit Windows.

**Comment by htzh** [comment] 2015-10-11 00:02
@maxirmx Good to know. Thanks.

**Comment by honnibal** [comment] 2015-10-11 03:32
Nice progress. Let's keep pushing through, I think we're pretty close to resolving all this.

First, let's test all the individual components to check whether it's a data file issue.

I've added a file tests/test_basic_create.py , and pushed it to the master branch. You can get the file here:

https://raw.githubusercontent.com/honnibal/spaCy/693dd065479481ba4296fa932b913315b3a40b8d/tests/test_basic_create.py

The tests here don't use PyTest, so it'll be easier for you to run them.

So far these tests just create every class, without the data files, to make sure that the problem isn't in simple initialization. We'll then try loading the existing data in each class, and basic usage.

If you get a segfault, please try commenting out tests until we can hone in on the failing test.

**Comment by htzh** [comment] 2015-10-11 05:23
Both 32 bit and 64 bit passed the new test:
```
$ python3 test_basic_create.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.028s

OK
```

**Comment by maxirmx** [comment] 2015-10-11 08:14
Confirm. With 2.7 both 32 bit and 64 bit passed the new test.

BTW I do have py.test for all environments if it helps.  Tests fail because they are looking for de model.

**Comment by honnibal** [comment] 2015-10-11 08:48
Just pushed `tests/test_basic_load.py`

https://raw.githubusercontent.com/honnibal/spaCy/dba1daf5973a98c3c2472b96727257ec5e1bc08f/tests/test_basic_load.py

This loads the vocab, tagger and parser separately. Do they all load okay?

**Comment by maxirmx** [comment] 2015-10-11 10:50
Crashes on parser

**Comment by honnibal** [comment] 2015-10-11 11:17
But not tagger? Hmm.

**Comment by honnibal** [comment] 2015-10-11 11:40
Added some more tests to `tests/test_basic_load.py`

**Comment by honnibal** [comment] 2015-10-11 11:47
This line might be suspicious:

https://github.com/honnibal/thinc/blob/master/thinc/learner.pyx#L290

```
feat = <SparseArrayC*>PyMem_Malloc((length + 1) * sizeof(SparseArrayC))
```

That's calling `sizeof()` on a struct. The relevant struct declaration:

https://github.com/honnibal/thinc/blob/master/thinc/sparse.pxd

Decoding the typedef, the struct is:

```
cdef struct SparseArrayC:
    int32_t key
    float val
```

I would've thought that'd be 64 bits on all platforms. Am I missing something?

**Comment by maxirmx** [comment] 2015-10-11 12:03
I would say it is 64 bits

**Comment by honnibal** [comment] 2015-10-11 13:47
Did you try the updated tests?

**Comment by maxirmx** [comment] 2015-10-11 13:59
Crashes. I am now uncommenting line by line

**Comment by maxirmx** [comment] 2015-10-11 14:20
`test_load_careful`   crashes at
`#        model = Model(moves.n_moves, templates, path.join(data_dir, 'deps'))`

`test_thinc_load`   passes

**Comment by maxirmx** [comment] 2015-10-11 14:20
I am sorry, no more support from me on this issue today

**Comment by honnibal** [comment] 2015-10-11 14:26
Okay, thanks.

My guess is that `test_thinc_load` might be only accidentally passing --- maybe the memory error is still there and we're just getting "lucky" and it's not crashing.

Anyway. I'll add some more tests, and hopefully we can resolve this tomorrow.

Thanks again!

**Comment by maxirmx** [comment] 2015-10-11 14:27
I will set up debug environment and there will be some stack.
A couple of ideas:
- Can it be casued by murmurhash headers mismatch ?
- I can run init_model  on win32 system. If there is data type mismatch it may help to make it work

**Comment by honnibal** [comment] 2015-10-14 15:37
Sorry, I lost track of this a bit. Are you blocking on me currently?

**Comment by maxirmx** [comment] 2015-10-14 17:04
No, not really.
I have other task in higher priority  :cry:

**Comment by maxirmx** [comment] 2015-10-21 22:13
There is 32/64 bits mismatch in processing of model binary files. Consider https://github.com/honnibal/spaCy/blob/master/spacy/strings.pyx#L141 

Dump function creates platform dependent file because Python unicode type is either 32-bits based or 64 bits based. It means that the model created on 64 bit system cannot be used on 32 bits system and vice versa. This explains the last issue discussed at  https://github.com/honnibal/spaCy/issues/132 because Python on Win32 uses 32 bits unicode type and the model downloaded by `python -m spacy.en.download` is 64 bits based

So if 32 bit support and model portability are considered it requires review of binary model files handling.

**Comment by htzh** [comment] 2015-10-22 01:33
@maxirmx Good find! Why save the file in unicode? Wouldn't that just blow up the size of the file? Seems like one would want to save either in binary or utf8.

**Comment by htzh** [comment] 2015-10-22 02:00
Copy from previous edit (so it goes through email):  If I understand it correctly, the function is first decoding the in-memory utf8 string into unicode and the codec then reencode unicode back into utf8 before saving. And @maxirmx is saying this process is 32/64 bit dependent. I don't know if that is right but at least it seems redundant without further understanding what Utf8Str* really is. I.e. why not dump Utf8Str* into a binary file?

I also read @maxirmx comment on https://github.com/honnibal/spaCy/issues/141 and now it makes sense. Seems to me read/write should be in binary mode and encoding format should be utf8 and it will be platform independent and save some cycles/memory as well.

**Comment by honnibal** [comment] 2015-10-22 03:47
The strings loading/saving should be switched to json. I've been meaning to do that for a while.

**Comment by maxirmx** [comment] 2015-10-22 08:18
Just be clear

``` Python
    def dump(self, loc):
        cdef Utf8Str* string
        cdef unicode py_string
        cdef int i
        with codecs.open(loc, 'w', 'utf8') as file_:
            for i in range(1, self.size):
                string = &self.c[i]
                py_string = _decode(string)
                file_.write(py_string)
                if (i+1) != self.size:
                    file_.write(SEPARATOR)
```

It is not writing\reading  Utf8Str, it is writing\reading unicode.
For example, write is: Utf8Str -conversion-> unicode -encoding-> utf8

Conversion is platform dependent and creates either 2 bytes or 4 bytes per char.

**Comment by maxirmx** [comment] 2015-10-22 08:28
The fix may be designed with different priorities in mind. It can be done it in a 'most effective way' which implies densed binary format or in a 'most readable way' which means json

**Comment by honnibal** [comment] 2015-10-22 09:10
I'm pretty skeptical about the details of your analysis here, but regardless the code is sloppy and should be corrected. So I'll take care of that.

The thing is, these are being written at the Python level, so the bit width for reading and writing shouldn't really matter. But still — I'll fix the code and we'll see where we are.

**Comment by honnibal** [comment] 2015-10-26 09:45
I've changed strings.txt to strings.json as of v0.97. So, please try again with that.

**Comment by honnibal** [comment] 2015-10-26 14:33
All builds now pass! Hooray.

Thanks a lot for your work on this.

**Comment by maxirmx** [comment] 2015-10-26 20:20
It looks like everybody lost  track of it so I will try to explain it from requirements or user stories if you like  down to the problem which may be there or may be not.

There is two dimensional Window build matrix:
Python:       3.4 or 2.7
Bus width:   32 or 64

However deployment\test matrix has the third dimension - the source of the model
Built locally by downloading wordnet and running init_model against it
Downloaded by spacy -m download

As of the morning Oct 25th the status was:

2.7-64-local                  build: OK    tests: OK
2.7-64-downloaded      build: OK    tests: OK
2.7-32-local                  build: OK    tests: OK
2.7-32-downloaded      build: OK    tests: Fail (seg fault)
3.4-64-local                  build: OK    tests: OK
3.4-64-downloaded      build: OK    tests: OK
3.4-32-local                  build: OK    tests: OK
3.4-32-downloaded      build: OK    tests: Not tested

I did not run tests with the downloaded model after the latest changes.

**Comment by maxirmx** [comment] 2015-10-26 20:27
Open questions regarding supported cases are:
1) Is 32bit Windows supported ?  
    - If "no" everything is OK
    - If "yes" there may be an issue depending on the next question
2) What is the "official" method to get the model ?
    - If it is running init_model locally everything is OK
    - If it downloading the model there may be an issue depending on the previous question

Also if "official" method is download it is not very good that all contnous integration test use init_model  -- they do not check the live case

**Comment by maxirmx** [comment] 2015-10-26 20:33
If 32bit Windows is supported and the right method to get model is to download it there was a bug there. The nature of the bug was somehow related to 32\64 incompatibility in model file handling.
At least the files generated by init_model in 32bit mode were different from those genererated in 64bit mode.

**Comment by honnibal** [comment] 2015-10-27 02:01
32 bit Windows support is intended. Can you provide details of the error please?

**Comment by maxirmx** [comment] 2015-10-27 16:25
The latest version terminates at `test_basic_load.py : test_load_careful`  calling `model = Model(moves.n_moves, templates, path.join(data_dir, 'deps'))`

It looks like an assert in thinc, but I am not sure. 
It looks like the latest version in git is 3.1 and on pypi - 3.3 so I cannot go further.

**Comment by honnibal** [comment] 2015-10-27 23:34
Pushed. Have a look now.

**Comment by maxirmx** [comment] 2015-10-29 07:02
It seems that heap is already corrupted at that point.

**Comment by maxirmx** [comment] 2015-11-02 09:27
(90% probability)

- weights object which is a part of Model tries to resize its Cells array to 32M items  (512 Mb memory)
- cymem.alloc fails   (PyMem_alloc return 0), system exception is thrown
- default compilation option is /EHa MSVC run-time creates structured exception and pushes it up the call chain
- cython wrappers attempt to deallocate objects but since exception happens in the middle of the resize, weiths is in inconsistent state (length is 32M, actual Cells array has only 16M items)
- LinearModel.__dealloc__ attempts to clean non-initialized entry in weights
*** Boom ***

**Comment by maxirmx** [comment] 2015-11-02 09:29
Multiply issues to research further:
- Why 512 Mb can not be allocated ?    
- Why 512 Mb ?  (check alignment)
- Compiler flags  (alignment, exception handling)
- Processing of memory allocation errors

**Comment by honnibal** [comment] 2015-11-02 13:57
Hmm.

Looking into this. cymem should fail earlier if allocation fails — this was pointed out to me a while ago and I never got around to fixing it. Doing that now.

What's `sizeof(size_t)` no Win32? I think technically `size_t` is the wrong type here. I should change this to use the Python pointer type.

**Comment by maxirmx** [comment] 2015-11-02 14:43
sizeof(size_t) == 4  for Win32

If you are fixing cymem there is one more issue there:   self.size += new_size  in realloc is redundant; you have already increased size in alloc.

**Comment by honnibal** [comment] 2015-11-02 15:43
Okay, pushed new version of `cymem` to PyPi. Unfortunately this meant also pushing new versions of thinc and preshed, because some of the data-structures changed size, so the .c and .cpp files had to be regenerated.

If you do:

```
git pull origin master
pip install -r requirements.txt
python setup.py build_ext --inplace
```

for thinc, that hopefully will work. If not, try:

```
pip install --upgrade cymem
pip install --upgrade preshed
python setup.py clean --all
python setup.py build_ext --inplace
```

**Comment by maxirmx** [comment] 2015-11-02 16:19
One more issue in cymem: 
```self.size += new_size``` in realloc is redundant because by that point size have been  increased in alloc already.

**Comment by maxirmx** [comment] 2015-11-02 16:26
I am running mixed mode (native code/Python) debugger so I am building with modified setups anyway. Git push would be enough.

Do you mind if I add compiler flag management to all projects as it has been done for spacy ?   It will save a lot of time for somebody if system-level problem is to be debugged in the future.

**Comment by honnibal** [comment] 2015-11-02 16:28
Sure, go ahead.

**Comment by maxirmx** [comment] 2015-11-02 22:21
With some small changes to cymem (https://github.com/syllog1sm/cymem/pull/4) and preshed (https://github.com/syllog1sm/preshed/pull/6) it now fails smoothly.

I believe the issue can be closed

```
Running test_basic_load.py
EEE...
======================================================================
ERROR: test_load (__main__.TestLoadParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spacy\tests\test_basic_load.py", line 55, in test_load
    parser = Parser.from_dir(path.join(data_dir, 'deps'), vocab.strings, ArcEager)
  File "spacy\syntax\parser.pyx", line 83, in spacy.syntax.parser.Parser.from_dir (spacy/syntax\parser.cpp:5748)
    model = Model(moves.n_moves, templates, model_dir)
  File "spacy\_ml.pyx", line 63, in spacy._ml.Model.__init__ (spacy\_ml.cpp:2962)
    self._model.load(self.model_loc, freq_thresh=0)
  File "thinc\learner.pyx", line 220, in thinc.learner.LinearModel.load (thinc/learner.cpp:4572)
    self.weights.set(feat_id, feature)
  File "preshed\maps.pyx", line 55, in preshed.maps.PreshMap.set (preshed/maps.c:2191)
    map_set(self.mem, self.c_map, key, <void*>value)
  File "preshed\maps.pyx", line 96, in preshed.maps.map_set (preshed/maps.c:2680)
    _resize(mem, map_)
  File "preshed\maps.pyx", line 157, in preshed.maps._resize (preshed/maps.c:3276)
    map_.cells = <Cell*>mem.alloc(new_size, sizeof(Cell))
  File "cymem\cymem.pyx", line 41, in cymem.cymem.Pool.alloc (cymem\cymem.c:1054)
    raise MemoryError("Error assigning %d bytes" % (number * elem_size))
MemoryError: Error assigning 536870912 bytes

======================================================================
ERROR: test_load_careful (__main__.TestLoadParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spacy\tests\test_basic_load.py", line 66, in test_load_careful
    model = Model(moves.n_moves, templates, path.join(data_dir, 'deps'))
  File "spacy\_ml.pyx", line 63, in spacy._ml.Model.__init__ (spacy\_ml.cpp:2962)
    self._model.load(self.model_loc, freq_thresh=0)
  File "thinc\learner.pyx", line 220, in thinc.learner.LinearModel.load (thinc/learner.cpp:4572)
    self.weights.set(feat_id, feature)
  File "preshed\maps.pyx", line 55, in preshed.maps.PreshMap.set (preshed/maps.c:2191)
    map_set(self.mem, self.c_map, key, <void*>value)
  File "preshed\maps.pyx", line 96, in preshed.maps.map_set (preshed/maps.c:2680)
    _resize(mem, map_)
  File "preshed\maps.pyx", line 157, in preshed.maps._resize (preshed/maps.c:3276)
    map_.cells = <Cell*>mem.alloc(new_size, sizeof(Cell))
  File "cymem\cymem.pyx", line 41, in cymem.cymem.Pool.alloc (cymem\cymem.c:1054)
    raise MemoryError("Error assigning %d bytes" % (number * elem_size))
MemoryError: Error assigning 268435456 bytes

======================================================================
ERROR: test_thinc_load (__main__.TestLoadParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "spacy\tests\test_basic_load.py", line 78, in test_thinc_load
    model.load(model_loc)
  File "thinc\learner.pyx", line 220, in thinc.learner.LinearModel.load (thinc/learner.cpp:4572)
    self.weights.set(feat_id, feature)
  File "preshed\maps.pyx", line 55, in preshed.maps.PreshMap.set (preshed/maps.c:2191)
    map_set(self.mem, self.c_map, key, <void*>value)
  File "preshed\maps.pyx", line 96, in preshed.maps.map_set (preshed/maps.c:2680)
    _resize(mem, map_)
  File "preshed\maps.pyx", line 157, in preshed.maps._resize (preshed/maps.c:3276)
    map_.cells = <Cell*>mem.alloc(new_size, sizeof(Cell))
  File "cymem\cymem.pyx", line 41, in cymem.cymem.Pool.alloc (cymem\cymem.c:1054)
    raise MemoryError("Error assigning %d bytes" % (number * elem_size))
MemoryError: Error assigning 536870912 bytes

----------------------------------------------------------------------
Ran 6 tests in 80.158s

FAILED (errors=3)```

**Comment by honnibal** [comment] 2015-12-29 11:42
v0.100, which we hope to release today, features fixed builds for both 32bit and 64bit Windows. The full matrix is being tested, results are shown on http://ci.spacy.io

I'm going to close this for now. If there are still problems once v0.100 is released, we can reopen.

**Closed by honnibal** 2015-12-29 11:42 UTC
