### ISSUE TITLE
NotADirectoryError: [Errno 20] when installing using PyCharm Project Interpreter

### ISSUE THREAD

**Issue by scottwernervt** [honnibal/spaCy#114] opened 2015-09-28 21:37 UTC
I am encountering the following error when installing to my virtualenv using Project Interpreter from PyCharm Community Edition 4.5.3.

    Collecting spacy
      Using cached spacy-0.93.tar.gz
        Complete output from command python setup.py egg_info:
        warning: build_py: byte-compiling is disabled, skipping.
        
        warning: install_lib: byte-compiling is disabled, skipping.
        
        zip_safe flag not set; analyzing archive contents...
        
        Installed /tmp/pycharm-packaging0.tmp/spacy/.eggs/headers_workaround-0.17-py3.4.egg
        running egg_info
        creating pip-egg-info/spacy.egg-info
        writing top-level names to pip-egg-info/spacy.egg-info/top_level.txt
        writing requirements to pip-egg-info/spacy.egg-info/requires.txt
        writing dependency_links to pip-egg-info/spacy.egg-info/dependency_links.txt
        writing pip-egg-info/spacy.egg-info/PKG-INFO
        writing manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
        warning: manifest_maker: standard file '-c' not found
        
        reading manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        writing manifest file 'pip-egg-info/spacy.egg-info/SOURCES.txt'
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pycharm-packaging0.tmp/spacy/setup.py", line 176, in <module>
            main(MOD_NAMES, use_cython)
          File "/tmp/pycharm-packaging0.tmp/spacy/setup.py", line 151, in main
            run_setup(exts)
          File "/tmp/pycharm-packaging0.tmp/spacy/setup.py", line 133, in run_setup
            headers_workaround.install_headers('murmurhash')
          File "/tmp/pycharm-packaging0.tmp/spacy/.eggs/headers_workaround-0.17-py3.4.egg/headers_workaround/__init__.py", line 30, in install_headers
        NotADirectoryError: [Errno 20] Not a directory: '/tmp/pycharm-packaging0.tmp/spacy/.eggs/headers_workaround-0.17-py3.4.egg/headers_workaround/murmurhash'
        
        ----------------------------------------

    Command "python setup.py egg_info" failed with error code 1 in /tmp/pycharm-packaging0.tmp/spacy

Workaround is to manually install using `venv/bin/pip3.4 install spacy`. Not sure why that works vs using PyCharm to install it using pip.

**Comment by honnibal** [comment] 2015-09-29 02:28
Thanks.

It looks like PyCharm has tweaked the installation process, to address some of the problems with setuptools. It seems this is conflicting with my own workaround, using this headers_workaround library.

I'll look into this.

**Comment by rincevm** [comment] 2015-10-28 07:12
same issue for me also. unable to install  packages in pycharm

error: byte-compiling is disabled.

**Comment by jmhobrien** [comment] 2015-11-16 02:49
I'm currently unable to use PyCharm 5 on Mavericks.

**Comment by tadgh** [comment] 2015-11-16 06:58
Chiming in to say that I've just encountered this as well. http://pastebin.com/wnQBAwf0

**Comment by jmhobrien** [comment] 2015-11-16 08:58
I created a new virtual environment within PyCharm and was able to get things working correctly.

**Comment by honnibal** [comment] 2015-12-02 13:08
First of all: as a user, I really hate installation problems of anything I'm using — I know it's super frustrating. So we really do care about making this easy. We're disappointed that we're still struggling with this, due to the diverse range of ways that setuptools and pip behave, and the general mess that is Python packaging for C extensions.

I'm working on this, and I'll tell you what I know for now.

1. This isn't a PyCharm specific problem. It also seems to be occurring for some users who install into the root directory. I haven't replicated this yet, but reports are clear.

2. The problem is occurring in the `headers_workaround` module, whose purpose is described here: https://github.com/syllog1sm/headers_workaround . Unfortunately the underlying bug that causes us to employ this hack is still present in setuptools: https://bitbucket.org/pypa/setuptools/issues/391/dependencies-listed-in-both-setup_requires . We're evaluating other ways around this, as the `headers_workaround` solution isn't playing nicely with wheel installations.

3. The specific error is arising here: https://github.com/syllog1sm/headers_workaround/blob/master/headers_workaround/__init__.py#L33 . It's saying that the `src_dir` path is not a directory. The intention in this code is:

- We're in `headers_workaround/__init__.py`
- We want to get a path to `headers_workaround/numpy` or `headers_workaround/murmurhash` (whichever one matches the `package_name` argument)
- The `_local_path` function builds this, by referring to the `__file__` special variable, which gives the path to the current module.
- Those directories are shipped as package-data

My suspicions at this point are that there's some sort of .egg zip file trickery, or some symlink problem.

I'm working on replicating the issue. Once I do a fix should be forth-coming. We'll continue working on the underlying causes of this sort of brittleness as well.

**Comment by honnibal** [comment] 2015-12-02 22:50
Super simple temporary solution I totally should've seen sooner:

    pip install headers_workaround
    pip install spacy

This worked for me with PyCharm 5.0

**Comment by demidovakatya** [comment] 2015-12-14 06:07
Hi,

PyCharm CE 5.0.2 (on mac) tries to install pip, then fails. I've installed `headers_workaround` and `spacy`, but it didn't work. Screenshot: https://dl.dropboxusercontent.com/u/9420368/pycharm.png

(On the other hand, I'm totally new to PyCharm and might have done something wrong.)

**Comment by lhuyuel** [comment] 2015-12-18 03:26
I encountered the same issue: 
> 40:357: execution error: warning: build_py: byte-compiling is disabled, skipping

(I'm using PyCharm5.0.2 on Yosemite, installed headers_workaround and spacy)

**Comment by honnibal** [comment] 2015-12-18 11:04
Ah, yes — you should be using Python 2.7+ or Python 3.4+

**Comment by honnibal** [comment] 2016-01-16 15:29
Tentatively closing this. @henningpeters has rewritten the setup.py process, removing the need for the brittle `headers_workaround` logic I had in place. This means that this sort of error should be resolved now.

The fix is currently in the master branch, and should be released shortly.

**Closed by honnibal** 2016-01-16 15:29 UTC
