### ISSUE TITLE
Problem with word frequency data?

### ISSUE THREAD

**Issue by Ejhfast** [honnibal/spaCy#10] opened 2015-01-27 16:32 UTC
When I follow the quick-start install steps, lexeme data exists at _/usr/local/lib/python2.7/dist-packages/spacy/en/data/vocab/lexemes.bin_, but somehow it isn't being loaded.

    import spacy.en
    nlp = spacy.en.English()
    nlp.vocab[u'the'].prob  #=> 0.0
    nlp.vocab[u'not'].prob  #=> 0.0

I've also tried loading manually with:

    nlp.vocab.load_lexemes("/usr/local/lib/python2.7/dist-packages/spacy/en/data/vocab/lexemes.bin")

**Comment by honnibal** [comment] 2015-01-27 16:44
Hmm.

I've never tested this without a virtualenv. I'd assumed it should load the same. I'll try to reproduce this now.

**Comment by honnibal** [comment] 2015-01-27 17:22
Yeah, it's working when I run it with the pyenv version, but not with the system Python. I've checked and the data's the same, and it's definitely getting loaded.

I suspect the most likely thing is that the way Python and spaCy are being compiled is making a difference. The code to load the binary data is rather brittle; I read the whole struct at once.

Can you run:

   python -c "import distutils.sysconfig; print distutils.sysconfig.get_config_var('CONFIG_ARGS')

And tell me what comes back?

**Comment by Ejhfast** [comment] 2015-01-27 18:44
Sure, thanks!

    '--enable-shared' '--prefix=/usr' '--enable-ipv6' '--enable-unicode=ucs4' '--with-dbmliborder=bdb:gdbm' '--with-system-expat' '--with-system-ffi' '--with-fpectl' 'CC=x86_64-linux-gnu-gcc' 'CFLAGS=-D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'

**Comment by honnibal** [comment] 2015-01-27 19:03
Right.

Yeah, I'm getting the same error with these flags:

    '--enable-shared' '--prefix=/usr' '--enable-ipv6' '--enable-unicode=ucs4' '--with-dbmliborder=bdb:gdbm'  -with-system-expat' '--with-system-ffi' '--with-fpectl' 'CC=x86_64-linux-gnu-gcc' 'CFLAGS=-D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'

And it's working with these flags, via pyenv:

    '--prefix=/home/pixie/.pyenv/versions/2.7.8' '--libdir=/home/pixie/.pyenv/versions/2.7.8/lib' 'LDFLAGS=-L/home/pixie/.pyenv/versions/2.7.8/lib ' 'CPPFLAGS=-I/home/pixie/.pyenv/versions/2.7.8/include '

I'll look into this, thanks for the report.

**Comment by honnibal** [comment] 2015-01-28 05:43
Okay, the issue is with the --enable-unicode=ucs4 compile flag.

The lexemes.bin file currently contains the output of hashing unicode strings. On wide unicode builds these produce different values, so all string-lookups are failing.

The simple fix is to have the lexemes.bin file refer to indices into the strings.txt file. This way the hashes can be recomputed on the target platform. I should be able to roll this out fairly quickly.

**Comment by honnibal** [comment] 2015-02-01 03:52
Now fixed.

**Comment by Ejhfast** [comment] 2015-02-01 23:10
Awesome, thanks!

**Comment by simonwiles** [comment] 2015-07-21 19:04
Are words missing frequency data likely to be related to the same issue?

    import spacy.en
    nlp = spacy.en.English()
    nlp.vocab[u'the'].prob  #=> -3.078474521636963
    nlp.vocab[u'not'].prob  #=> -5.407193660736084
    nlp.vocab[u'Darwin'].prob  #=> -12.803827285766602
    nlp.vocab[u'allele'].prob  #=> 0.0

Is there something I can do about this?

**Comment by honnibal** [comment] 2015-07-25 21:16
Hi, sorry about the delay replying to this.

You're right that this part of the data is a bit broken. There were actually a few problems here:

1. Out-of-vocabulary words get the probability 0. This is the most frustrating, as it's exactly wrong, given that the rest of the distribution is in log space, so these were sorting higher.
2. The counts were based on newswire text (Gigaword corpus) which isn't great for most users.
3. There was a bug in my smoothing code.

The new release uses counts derived from the Reddit comment corpus --- 60 billion tokens. I've also taken care to fix the other associated bugs as well.

I hope to have a release candidate out soon. I'll send it your way for testing when I do.

**Comment by simonwiles** [comment] 2015-07-26 19:09
That's great, thanks; I'll look forward to the RC.

**Comment by honnibal** [comment] 2015-07-29 03:40
Okay, v0.89 is now up on PyPI: http://spacy.io/updates.html . Give it a go!

**Comment by simonwiles** [comment] 2015-07-29 04:51
Looks great, thanks!

    import spacy.en
    nlp = spacy.en.English()
    nlp.vocab[u'the'].prob  #=> -3.528766632080078
    nlp.vocab[u'not'].prob  #=> -5.332601070404053
    nlp.vocab[u'Darwin'].prob  #=> -12.72145938873291
    nlp.vocab[u'allele'].prob  #=> -14.982345581054688

**Closed** 2015-08-26 19:16 UTC
