### ISSUE TITLE
Merging spans in noisy text can affect sentence splitting and subtree property

### ISSUE THREAD

**Issue by andreasgrv** [honnibal/spaCy#188] opened 2015-11-23 16:42 UTC
After merging named entities in noisy text most of the times everything works fine, however sometimes unexpected things happen! ^_^

``` python
doc = nlp(u'A popcorn named John Spik added a weird url after a question mark? http://www.what-why.com\n')
for sent in doc.sents:
    print('%s : [%s, %s]' % (sent, sent.start, sent.end))
```
out:

    A popcorn named John Spik added a weird url after a question mark? : [0, 14]
    http://www.what-why.com
     : [14, 18]

``` python
for ent in doc.ents:                                                                                                                        
    ent.merge(ent.root.tag_ , ent.text, ent.label_)

for sent in doc.sents:
    print('%s : [%s, %s]' % (sent, sent.start, sent.end))
```
out:

    A popcorn named John Spik added a weird url after a question mark? : [0, 13]
    http://www.what : [13, 14]
    -why.com : [14, 16]
      : [16, 17]   # this is the \n

``` python
doc = nlp(u'RT 136 children killed in Peshawar Everyone Outraged 3000 Yezidi kids killed by ISIS - every 1 Silent? http://…\n')
for sent in doc.sents:
    print(list(sent.root.subtree))
```

    [RT , 136 , children , killed , in , Peshawar , Everyone , Outraged , 3000 , Yezidi , kids , killed , by , ISIS , - , every , 1 , Silent, ? ]
    [http://…]

 ``` python
for ent in doc.ents:                                                                                                                        
    ent.merge(ent.root.tag_ , ent.text, ent.label_)

for sent in doc.sents:
    print(list(sent.root.subtree))
```

state:

    Infinite recursion

**Comment by honnibal** [comment] 2015-11-27 09:42
Thanks. I made a change that was supposed to prevent the NER from tagging entities across sentence boundaries. It looks like I introduced this bug from that change. I'll have a look at this.

(Sorry I've been a bit slow on the bug fixes the last week or two. I've had my head down trying to finish the neural network code, to update the model. According to published results this should improve accuracy, and cut memory usage substantially.)

**Comment by andreasgrv** [comment] 2015-11-27 09:47
Nice :+1:
No worries, I've currently just commented out the merging part of the code

**Comment by honnibal** [comment] 2016-01-19 13:22
This was caused by the same problem as Issue #214 , so I think my fix there applies. Your example is working on master for me now, and should be fixed in v100, which will be out shortly.

Thanks for your patience!

**Comment by andreasgrv** [comment] 2016-01-19 13:32
Nice :+1: 

Thanks for the fix, will check it out!

**Comment by honnibal** [comment] 2016-01-19 22:18
Just pushed v0.100, which should have this fixed. If you have any problems, please reopen this and let us know.

**Closed by honnibal** 2016-01-19 22:18 UTC
Labels: bug
